id: PCC9E8EE9
initial_creation_type: input
source_metadata:
  title: Tenth Pawo Rinpoche Series
  language: bo
  description: 'Texts by and about the Tenth Pawo Rinpoche, Tsuklak Mawé Wangchuk
    (gtsug lag smra ba’i dbang phyug, 1912–1991):'
  volume:
    55357cf5461e405d9bd3fc8ecf74096d:
      title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
      parent: Guru Yoga
created_at: '2022-03-01T01:41:05.538167'
last_modified_at: '2022-03-01T01:41:05.538170'
statistics:
  total_words: 278
  total_non_words: 13
quality:
  non_words_ratio: 0.05
